spring:
  application:
    name: shows-service

  profiles:
    active: dev

  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shows_service
    username: myuser
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 3600000

server:
  port: 8083

api-gateway:
  url: http://localhost:8080

user-service:
  api:
    url: http://localhost:8082

review-rating-service:
  api:
    url: http://localhost:8084

tv-maze:
  api:
    url: https://api.tvmaze.com
    size: 250

logging:
  level:
    root: INFO
    com.example.tvshows_service: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
