services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=review_rating_service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5435:5432'
