services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shows_service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'