server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - AddRequestHeader=X-API-Version, v1
            - id: user-service-profiles
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**
              filters:
                - AddRequestHeader=X-API-Version, v1
            - id: user-service-watchlist
              uri: http://localhost:8082
              predicates:
                - Path=/api/watchlist/**
              filters:
                - AddRequestHeader=X-API-Version, v1

            - id: tv-shows-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/tv-shows/**
              filters:
                - AddRequestHeader=X-API-Version, v1

            - id: review-rating-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/review/**
              filters:
                - AddRequestHeader=X-API-Version, v1

jwt:
  secret: a3f9b1c8d4e7f0a3b9c2d1e8f6a7b4c5d3e2f1a9b8c7d6e5f4a3b2c1d0e9f8a7

logging:
  level:
    org.springframework.cloud.gateway: DEBUG